# Generated by Django 4.1.2 on 2024-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_helmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helmet',
            name='numberplate',
            field=models.FileField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='rider',
            field=models.FileField(blank=True, null=True, upload_to='posts'),
        ),
    ]
